import { TTimeTableFormatted } from './model';

export const input: TTimeTableFormatted[] = [
  {
    fromTime: '09:00',
    action: 'SetTeamStatus',
    toTime: '10:30',
    status: 'busy',
    source: 'team',
    importance: 10,
    type: 'exception',
  },
  {
    fromTime: '09:00',
    action: 'SetTeamStatus',
    toTime: '10:40',
    status: 'steady',
    source: 'team',
    importance: 5,
    type: 'standard',
  },
  {
    fromTime: '13:05',
    action: 'SetTeamStatus',
    toTime: '13:06',
    status: 'busy',
    source: 'team',
    importance: 10,
    type: 'exception',
  },
  {
    fromTime: '13:27',
    action: 'SetTeamStatus',
    toTime: '16:00',
    status: 'steady',
    source: 'company',
    importance: 3,
    type: 'standard',
  },
  {
    fromTime: '14:00',
    action: 'SetTeamStatus',
    toTime: '16:00',
    status: 'steady',
    source: 'team',
    importance: 5,
    type: 'standard',
  },
  {
    fromTime: '16:00',
    action: 'SetTeamStatus',
    toTime: '16:35',
    status: 'steady',
    source: 'team',
    importance: 5,
    type: 'standard',
  },
];
