import { TTimeTableFormatted } from './model';

export const input: TTimeTableFormatted[] = [
  {
    fromTime: '09:00',
    action: 'SetTeamStatus',
    toTime: '10:30',
    status: 'busy',
    source: 'team',
    importance: 10,
    type: 'exception',
  },
  {
    fromTime: '09:00',
    action: 'SetTeamStatus',
    toTime: '12:00',
    status: 'steady',
    source: 'branch',
    importance: 9,
    type: 'exception',
  },
  {
    fromTime: '12:00',
    action: 'SetTeamStatus',
    toTime: '17:00',
    status: 'quiet',
    source: 'branch',
    importance: 9,
    type: 'exception',
  },
  {
    fromTime: '13:05',
    action: 'SetTeamStatus',
    toTime: '13:06',
    status: 'busy',
    source: 'team',
    importance: 10,
    type: 'exception',
  },
  {
    fromTime: '14:00',
    action: 'SetTeamStatus',
    toTime: '16:00',
    status: 'steady',
    source: 'branch',
    importance: 4,
    type: 'standard',
  },
  {
    fromTime: '15:35',
    action: 'SetTeamStatus',
    toTime: '16:00',
    status: 'steady',
    source: 'branch',
    importance: 4,
    type: 'standard',
  },
];
